version: '3.1'

services:
  db:
        image: mysql
        container_name: discussion-db
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_ALLOW_EMPTY_PASSWORD: 0 
            MYSQL_DATABASE: microservice-discussions
        healthcheck:
            test: ["CMD", "mysql", "--user=root", "--password=root", "--execute=SHOW DATABASES;"]
            interval: 10s
            retries: 5
        
  server:
      build: src
      container_name: microservice-discussion
      restart: always
      expose:
        - 8080
      ports:
        - 8080:8080
      depends_on:
          - db

